%-----------------------------------------------------------------------
% Job saved on 02-Dec-2023 10:11:59 by cfg_util (rev $Rev: 7345 $)
% spm SPM - SPM12 (7771)
% cfg_basicio BasicIO - Unknown
%-----------------------------------------------------------------------
matlabbatch{1}.spm.dcm.spec.fmri.group.output.dir = {'/Users/user/data/DCM - PEB'};
matlabbatch{1}.spm.dcm.spec.fmri.group.output.name = 'full';
matlabbatch{1}.spm.dcm.spec.fmri.group.template.fulldcm = {'/Users/user/DCM_example_not_inverted.mat'};
%%
matlabbatch{1}.spm.dcm.spec.fmri.group.template.altdcm = {
                                                          };
%%
%%
%%
matlabbatch{1}.spm.dcm.spec.fmri.group.data.spmmats = {
                                                       '/Users/user/data/001/results/SPM.mat'
                                                       '/Users/user/data/002/results/SPM.mat'
                                                       '/Users/user/data/003/results/SPM.mat'
                                                       '/Users/user/data/004/results/SPM.mat'
                                                       '/Users/user/data/006/results/SPM.mat'
                                                       '/Users/user/data/007/results/SPM.mat'
                                                       '/Users/user/data/008/results/SPM.mat'
                                                       '/Users/user/data/010/results/SPM.mat'
                                                       '/Users/user/data/011/results/SPM.mat'
                                                       '/Users/user/data/012/results/SPM.mat'
                                                       '/Users/user/data/013/results/SPM.mat'
                                                       '/Users/user/data/014/results/SPM.mat'
                                                       '/Users/user/data/015/results/SPM.mat'
                                                       '/Users/user/data/017/results/SPM.mat'
                                                       '/Users/user/data/018/results/SPM.mat'
                                                       '/Users/user/data/019/results/SPM.mat'
                                                       };
%%
matlabbatch{1}.spm.dcm.spec.fmri.group.data.session = 1;
%%
matlabbatch{1}.spm.dcm.spec.fmri.group.data.region = {
                                                      {
                                                      '/Users/user/data/001/results/VOI_gg_left_IPG_1.mat'
                                                      '/Users/user/data/002/results/VOI_gg_left_IPG_1.mat'
                                                      '/Users/user/data/003/results/VOI_gg_left_IPG_1.mat'
                                                      '/Users/user/data/004/results/VOI_gg_left_IPG_1.mat'
                                                      '/Users/user/data/006/results/VOI_gg_left_IPG_1.mat'
                                                      '/Users/user/data/007/results/VOI_gg_left_IPG_1.mat'
                                                      '/Users/user/data/008/results/VOI_gg_left_IPG_1.mat'
                                                      '/Users/user/data/010/results/VOI_gg_left_IPG_1.mat'
                                                      '/Users/user/data/011/results/VOI_gg_left_IPG_1.mat'
                                                      '/Users/user/data/012/results/VOI_gg_left_IPG_1.mat'
                                                      '/Users/user/data/013/results/VOI_gg_left_IPG_1.mat'
                                                      '/Users/user/data/014/results/VOI_gg_left_IPG_1.mat'
                                                      '/Users/user/data/015/results/VOI_gg_left_IPG_1.mat'
                                                      '/Users/user/data/017/results/VOI_gg_left_IPG_1.mat'
                                                      '/Users/user/data/018/results/VOI_gg_left_IPG_1.mat'
                                                      '/Users/user/data/019/results/VOI_gg_left_IPG_1.mat'
                                                      }
                                                      {
                                                      '/Users/user/data/001/results/VOI_gg_left_SMA_1.mat'
                                                      '/Users/user/data/002/results/VOI_gg_left_SMA_1.mat'
                                                      '/Users/user/data/003/results/VOI_gg_left_SMA_1.mat'
                                                      '/Users/user/data/004/results/VOI_gg_left_SMA_1.mat'
                                                      '/Users/user/data/006/results/VOI_gg_left_SMA_1.mat'
                                                      '/Users/user/data/007/results/VOI_gg_left_SMA_1.mat'
                                                      '/Users/user/data/008/results/VOI_gg_left_SMA_1.mat'
                                                      '/Users/user/data/010/results/VOI_gg_left_SMA_1.mat'
                                                      '/Users/user/data/011/results/VOI_gg_left_SMA_1.mat'
                                                      '/Users/user/data/012/results/VOI_gg_left_SMA_1.mat'
                                                      '/Users/user/data/013/results/VOI_gg_left_SMA_1.mat'
                                                      '/Users/user/data/014/results/VOI_gg_left_SMA_1.mat'
                                                      '/Users/user/data/015/results/VOI_gg_left_SMA_1.mat'
                                                      '/Users/user/data/017/results/VOI_gg_left_SMA_1.mat'
                                                      '/Users/user/data/018/results/VOI_gg_left_SMA_1.mat'
                                                      '/Users/user/data/019/results/VOI_gg_left_SMA_1.mat'
                                                      }
                                                      {
                                                      '/Users/user/data/001/results/VOI_gg_left_dlPFC_1.mat'
                                                      '/Users/user/data/002/results/VOI_gg_left_dlPFC_1.mat'
                                                      '/Users/user/data/003/results/VOI_gg_left_dlPFC_1.mat'
                                                      '/Users/user/data/004/results/VOI_gg_left_dlPFC_1.mat'
                                                      '/Users/user/data/006/results/VOI_gg_left_dlPFC_1.mat'
                                                      '/Users/user/data/007/results/VOI_gg_left_dlPFC_1.mat'
                                                      '/Users/user/data/008/results/VOI_gg_left_dlPFC_1.mat'
                                                      '/Users/user/data/010/results/VOI_gg_left_dlPFC_1.mat'
                                                      '/Users/user/data/011/results/VOI_gg_left_dlPFC_1.mat'
                                                      '/Users/user/data/012/results/VOI_gg_left_dlPFC_1.mat'
                                                      '/Users/user/data/013/results/VOI_gg_left_dlPFC_1.mat'
                                                      '/Users/user/data/014/results/VOI_gg_left_dlPFC_1.mat'
                                                      '/Users/user/data/015/results/VOI_gg_left_dlPFC_1.mat'
                                                      '/Users/user/data/017/results/VOI_gg_left_dlPFC_1.mat'
                                                      '/Users/user/data/018/results/VOI_gg_left_dlPFC_1.mat'
                                                      '/Users/user/data/019/results/VOI_gg_left_dlPFC_1.mat'
                                                      }
                                                      {
                                                      '/Users/user/data/001/results/VOI_gg_right_IPG_1.mat'
                                                      '/Users/user/data/002/results/VOI_gg_right_IPG_1.mat'
                                                      '/Users/user/data/003/results/VOI_gg_right_IPG_1.mat'
                                                      '/Users/user/data/004/results/VOI_gg_right_IPG_1.mat'
                                                      '/Users/user/data/006/results/VOI_gg_right_IPG_1.mat'
                                                      '/Users/user/data/007/results/VOI_gg_right_IPG_1.mat'
                                                      '/Users/user/data/008/results/VOI_gg_right_IPG_1.mat'
                                                      '/Users/user/data/010/results/VOI_gg_right_IPG_1.mat'
                                                      '/Users/user/data/011/results/VOI_gg_right_IPG_1.mat'
                                                      '/Users/user/data/012/results/VOI_gg_right_IPG_1.mat'
                                                      '/Users/user/data/013/results/VOI_gg_right_IPG_1.mat'
                                                      '/Users/user/data/014/results/VOI_gg_right_IPG_1.mat'
                                                      '/Users/user/data/015/results/VOI_gg_right_IPG_1.mat'
                                                      '/Users/user/data/017/results/VOI_gg_right_IPG_1.mat'
                                                      '/Users/user/data/018/results/VOI_gg_right_IPG_1.mat'
                                                      '/Users/user/data/019/results/VOI_gg_right_IPG_1.mat'
                                                      }
                                                      {
                                                      '/Users/user/data/001/results/VOI_gg_right_Precuneus_1.mat'
                                                      '/Users/user/data/002/results/VOI_gg_right_Precuneus_1.mat'
                                                      '/Users/user/data/003/results/VOI_gg_right_Precuneus_1.mat'
                                                      '/Users/user/data/004/results/VOI_gg_right_Precuneus_1.mat'
                                                      '/Users/user/data/006/results/VOI_gg_right_Precuneus_1.mat'
                                                      '/Users/user/data/007/results/VOI_gg_right_Precuneus_1.mat'
                                                      '/Users/user/data/008/results/VOI_gg_right_Precuneus_1.mat'
                                                      '/Users/user/data/010/results/VOI_gg_right_Precuneus_1.mat'
                                                      '/Users/user/data/011/results/VOI_gg_right_Precuneus_1.mat'
                                                      '/Users/user/data/012/results/VOI_gg_right_Precuneus_1.mat'
                                                      '/Users/user/data/013/results/VOI_gg_right_Precuneus_1.mat'
                                                      '/Users/user/data/014/results/VOI_gg_right_Precuneus_1.mat'
                                                      '/Users/user/data/015/results/VOI_gg_right_Precuneus_1.mat'
                                                      '/Users/user/data/017/results/VOI_gg_right_Precuneus_1.mat'
                                                      '/Users/user/data/018/results/VOI_gg_right_Precuneus_1.mat'
                                                      '/Users/user/data/019/results/VOI_gg_right_Precuneus_1.mat'
                                                      }
                                                      {
                                                      '/Users/user/data/001/results/VOI_gg_right_dlPFC_1.mat'
                                                      '/Users/user/data/002/results/VOI_gg_right_dlPFC_1.mat'
                                                      '/Users/user/data/003/results/VOI_gg_right_dlPFC_1.mat'
                                                      '/Users/user/data/004/results/VOI_gg_right_dlPFC_1.mat'
                                                      '/Users/user/data/006/results/VOI_gg_right_dlPFC_1.mat'
                                                      '/Users/user/data/007/results/VOI_gg_right_dlPFC_1.mat'
                                                      '/Users/user/data/008/results/VOI_gg_right_dlPFC_1.mat'
                                                      '/Users/user/data/010/results/VOI_gg_right_dlPFC_1.mat'
                                                      '/Users/user/data/011/results/VOI_gg_right_dlPFC_1.mat'
                                                      '/Users/user/data/012/results/VOI_gg_right_dlPFC_1.mat'
                                                      '/Users/user/data/013/results/VOI_gg_right_dlPFC_1.mat'
                                                      '/Users/user/data/014/results/VOI_gg_right_dlPFC_1.mat'
                                                      '/Users/user/data/015/results/VOI_gg_right_dlPFC_1.mat'
                                                      '/Users/user/data/017/results/VOI_gg_right_dlPFC_1.mat'
                                                      '/Users/user/data/018/results/VOI_gg_right_dlPFC_1.mat'
                                                      '/Users/user/data/019/results/VOI_gg_right_dlPFC_1.mat'
                                                      }
                                                      }';
%%